
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-10
owner: ucsb-cs156-f24
repo_name: team01-f24-10
pull_requests: [{"author":{"id":"U_kgDOBtnxJw","is_bot":false,"login":"DderrickLee","name":""},"headRefName":"Derrick-UpdateReadMeTable","number":63,"title":"Derrick update read me table","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/63"},{"author":{"id":"MDQ6VXNlcjI1MzQwNzk1","is_bot":false,"login":"AjayLiu","name":"AjayLiu"},"headRefName":"ajay-delete-articles","number":54,"title":"Ajay -  Delete Endpoint for Articles","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/54"}]
