
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-10
owner: ucsb-cs156-f24
repo_name: team01-f24-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjI1MzQwNzk1","is_bot":false,"login":"AjayLiu","name":"AjayLiu"},"headRefName":"ajay-put-articles","number":53,"title":"Ajay put articles","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/53"},{"author":{"id":"MDQ6VXNlcjI1MzQwNzk1","is_bot":false,"login":"AjayLiu","name":"AjayLiu"},"headRefName":"ajay-get-all-articles","number":52,"title":"Ajay get all articles","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/52"},{"author":{"id":"MDQ6VXNlcjI1MzQwNzk1","is_bot":false,"login":"AjayLiu","name":"AjayLiu"},"headRefName":"ajay-create-articles-controller","number":51,"title":"Ajay create articles controller","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/51"},{"author":{"id":"U_kgDOBtxmHw","is_bot":false,"login":"justinwu13","name":"Justin Wu"},"headRefName":"Justin-UCSBDiningCommonsMenuItem-edit","number":50,"title":"Add edit method to UCSBDiningCommonsMenuItem controller + tests","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/50"},{"author":{"id":"MDQ6VXNlcjMzNzMyMzky","is_bot":false,"login":"r0ckwav3","name":"Peter"},"headRefName":"Peter-UCSBOrganizationTable-Controller","number":49,"title":"Add Ucsb Organization Table Controller","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/49"},{"author":{"id":"U_kgDOBtxmHw","is_bot":false,"login":"justinwu13","name":"Justin Wu"},"headRefName":"Justin-UCSBDiningCommonsMenuItem-get-single","number":48,"title":"Added single get method for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/48"},{"author":{"id":"U_kgDOBtnxJw","is_bot":false,"login":"DderrickLee","name":""},"headRefName":"Derrick-MenuItemReview-create-db","number":47,"title":"Issue #26","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/47"}]
