
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-10
owner: ucsb-cs156-f24
repo_name: team01-f24-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjMzNzMyMzky","is_bot":false,"login":"r0ckwav3","name":"Peter"},"headRefName":"Peter-UCSBOrganization-Delete","number":60,"title":"Peter - Add UCSB organization delete endpoint","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/60"},{"author":{"id":"U_kgDOBtnxJw","is_bot":false,"login":"DderrickLee","name":""},"headRefName":"Derrick-MenuItemReview-Delete","number":59,"title":"Derrick menu item review delete","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/59"},{"author":{"id":"MDQ6VXNlcjMzNzMyMzky","is_bot":false,"login":"r0ckwav3","name":"Peter"},"headRefName":"Peter-UCSBOrganization-Put","number":58,"title":"Peter Add Put oendpoint to UCSBOrganization","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/58"},{"author":{"id":"U_kgDOBtnxJw","is_bot":false,"login":"DderrickLee","name":""},"headRefName":"Derrick-MenuItemReview-create-db","number":57,"title":"Added MenuItemReviewController with methods GET and Post. Added MenuI…","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/57"},{"author":{"id":"U_kgDOBtxmHw","is_bot":false,"login":"justinwu13","name":"Justin Wu"},"headRefName":"Justin-UCSBDiningCommonsMenuItem-delete","number":56,"title":"Add delete method for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/56"},{"author":{"id":"MDQ6VXNlcjI1MzQwNzk1","is_bot":false,"login":"AjayLiu","name":"AjayLiu"},"headRefName":"ajay-delete-articles","number":54,"title":"Ajay -  Delete Endpoint for Articles","url":"https://github.com/ucsb-cs156-f24/team01-f24-10/pull/54"}]
